[REVIEW][FEATURE][GAWE-53] - Set Reset Password
Blue-Habit/gawean-rest-api pull request #5
Opened 2023-08-11 07:24 UTC by saddam-satria

#### Description

> After Clicking password reset request link, user should set reset password by token

#### Ticket Reference(s)

[GAWE-53](https://bluehabit.atlassian.net/browse/GAWE-53)

#### Validation

##### UI Changes

> Screenshot or video of UI-related changes

##### Coverage

> Test coverage screenshot.

N/A

#### Note(s)

> Couldnt testing yet, because have different model on user credential, but user can reset their password, I will testing later

2023-08-11 10:20 UTC, triandamai requested changes
Cek dulu ya

2023-08-11 10:20 UTC, triandamai commented on src/main/java/com/bluehabit/eureka/common/AbstractBaseService.java
> -/*
Ini knp di remove ya?

2023-08-11 10:20 UTC, triandamai commented on src/main/java/com/bluehabit/eureka/component/user/UserVerification.java
> +
Pakein annotation aja `@Getter` dan `@Setter` jadi ga perlu setter getter..kecuali diperlukan

2023-08-11 10:20 UTC, triandamai commented on src/main/java/com/bluehabit/eureka/controller/ResetPasswordController.java
>          @RequestBody ResetPasswordRequest request
Gabungin aj sama AuthenticationController

2023-08-11 10:20 UTC, triandamai commented on src/main/java/com/bluehabit/eureka/services/user/ResetPasswordService.java
> +        } catch (UnAuthorizedException exception) {
Ga perlu pake try catch ya..karena otomatis throwable masuk ke errorcontroller

2023-08-11 10:20 UTC, triandamai commented on src/main/java/com/bluehabit/eureka/services/user/ResetPasswordService.java
> +                throw new UnAuthorizedException(HttpStatus.NOT_FOUND.value(), translate("auth.token.invalid"));
Klo mau buat selain UnAuthorize pake aja `throw new GeneralErrorException`

2023-08-11 10:37 UTC, saddam-satria commented on src/main/java/com/bluehabit/eureka/common/AbstractBaseService.java
> -/*
itu tadi copy dari yg terbaru abstractnya, di grub katanya conflct kan

2023-08-11 13:22 UTC, triandamai requested changes
dikit lagi ya

2023-08-11 13:22 UTC, triandamai commented on src/main/java/com/bluehabit/eureka/component/user/UserVerification.java
>      @Column
ganti pake `@Enumerated(EnumType.ORDINAL)`

2023-08-11 13:22 UTC, triandamai commented on src/main/java/com/bluehabit/eureka/controller/AuthenticationController.java
> +        @RequestHeader(value = "4adf-3ed", required = false) String token,
taro di `Constant` aja ya

2023-08-11 13:22 UTC, triandamai commented on src/main/java/com/bluehabit/eureka/services/user/ResetPasswordService.java
> +    private UserVerificationRepository userVerificationRepository;
kasih `@Autowired` ya biar ter inject

2023-08-11 13:22 UTC, triandamai commented on src/main/java/com/bluehabit/eureka/services/user/ResetPasswordService.java
> +    private UserCredentialRepository userCredentialRepository;
kasih `@Autowired` ya biar ter inject

2023-08-11 13:22 UTC, triandamai commented on src/main/java/com/bluehabit/eureka/services/user/ResetPasswordService.java
> +@AllArgsConstructor
ga perlu pake ini ya

2023-08-11 13:30 UTC, saddam-satria commented on src/main/java/com/bluehabit/eureka/services/user/ResetPasswordService.java
> +    private UserVerificationRepository userVerificationRepository;
itu udah ke inject kak, pake lombok

2023-08-11 13:36 UTC, triandamai commented on src/main/java/com/bluehabit/eureka/services/user/ResetPasswordService.java
> +    private UserVerificationRepository userVerificationRepository;
lombok nya kita pake buat generate Data aja....klo buat dependency injection pake bawaan aja Autowired biar konsisten

2023-08-11 13:45 UTC, saddam-satria commented on src/main/java/com/bluehabit/eureka/services/user/ResetPasswordService.java
> +    private UserVerificationRepository userVerificationRepository;
oke dah saya push ya

2023-08-12 13:45 UTC, triandamai approved these changes

2023-08-13 14:11 UTC, merged